### ISSUE TITLE
pak ini gimana dia gak bisa memanggil navbar nya

### ISSUE THREAD

**Issue by sudeshratch** [gymie/mahasiswaapp#1]
![Screenshot_5](https://user-images.githubusercontent.com/55694500/66890644-fca00800-f010-11e9-93ca-06ec2dbc9139.png)

**Comment by gymie** [comment]
itu kamu ada manggil route dengan nama list_mhs.. cek kembali di web.php apakah kamu ada definisikan route dengan name tersebut.. cthnya 

    route::get("/list","mahasiswacontroller@list")->name("list_mhs")
